package entite;
// Generated 2018-05-16 08:56:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private BigDecimal nocommande;
     private Client client;
     private Date datecommande;

    public Commande() {
    }

    public Commande(BigDecimal nocommande, Client client, Date datecommande) {
       this.nocommande = nocommande;
       this.client = client;
       this.datecommande = datecommande;
    }
   
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }




}


