package entity;
// Generated May 21, 2018 1:50:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private BigDecimal nocommande;
     private Client client;
     private Date datecommande;
     private Set lignecommandes = new HashSet(0);

    public Commande() {
    }

	
    public Commande(BigDecimal nocommande, Client client, Date datecommande) {
        this.nocommande = nocommande;
        this.client = client;
        this.datecommande = datecommande;
    }
    public Commande(BigDecimal nocommande, Client client, Date datecommande, Set lignecommandes) {
       this.nocommande = nocommande;
       this.client = client;
       this.datecommande = datecommande;
       this.lignecommandes = lignecommandes;
    }
   
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public Set getLignecommandes() {
        return this.lignecommandes;
    }
    
    public void setLignecommandes(Set lignecommandes) {
        this.lignecommandes = lignecommandes;
    }




}


