package entity;
// Generated May 21, 2018 1:50:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetaillivraisonId generated by hbm2java
 */
public class DetaillivraisonId  implements java.io.Serializable {


     private BigDecimal nolivraison;
     private BigDecimal nocommande;
     private BigDecimal noarticle;

    public DetaillivraisonId() {
    }

    public DetaillivraisonId(BigDecimal nolivraison, BigDecimal nocommande, BigDecimal noarticle) {
       this.nolivraison = nolivraison;
       this.nocommande = nocommande;
       this.noarticle = noarticle;
    }
   
    public BigDecimal getNolivraison() {
        return this.nolivraison;
    }
    
    public void setNolivraison(BigDecimal nolivraison) {
        this.nolivraison = nolivraison;
    }
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public BigDecimal getNoarticle() {
        return this.noarticle;
    }
    
    public void setNoarticle(BigDecimal noarticle) {
        this.noarticle = noarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetaillivraisonId) ) return false;
		 DetaillivraisonId castOther = ( DetaillivraisonId ) other; 
         
		 return ( (this.getNolivraison()==castOther.getNolivraison()) || ( this.getNolivraison()!=null && castOther.getNolivraison()!=null && this.getNolivraison().equals(castOther.getNolivraison()) ) )
 && ( (this.getNocommande()==castOther.getNocommande()) || ( this.getNocommande()!=null && castOther.getNocommande()!=null && this.getNocommande().equals(castOther.getNocommande()) ) )
 && ( (this.getNoarticle()==castOther.getNoarticle()) || ( this.getNoarticle()!=null && castOther.getNoarticle()!=null && this.getNoarticle().equals(castOther.getNoarticle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNolivraison() == null ? 0 : this.getNolivraison().hashCode() );
         result = 37 * result + ( getNocommande() == null ? 0 : this.getNocommande().hashCode() );
         result = 37 * result + ( getNoarticle() == null ? 0 : this.getNoarticle().hashCode() );
         return result;
   }   


}


