package entity;
// Generated May 21, 2018 1:50:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detaillivraison generated by hbm2java
 */
public class Detaillivraison  implements java.io.Serializable {


     private DetaillivraisonId id;
     private Livraison livraison;
     private Lignecommande lignecommande;
     private BigDecimal quantitelivree;

    public Detaillivraison() {
    }

    public Detaillivraison(DetaillivraisonId id, Livraison livraison, Lignecommande lignecommande, BigDecimal quantitelivree) {
       this.id = id;
       this.livraison = livraison;
       this.lignecommande = lignecommande;
       this.quantitelivree = quantitelivree;
    }
   
    public DetaillivraisonId getId() {
        return this.id;
    }
    
    public void setId(DetaillivraisonId id) {
        this.id = id;
    }
    public Livraison getLivraison() {
        return this.livraison;
    }
    
    public void setLivraison(Livraison livraison) {
        this.livraison = livraison;
    }
    public Lignecommande getLignecommande() {
        return this.lignecommande;
    }
    
    public void setLignecommande(Lignecommande lignecommande) {
        this.lignecommande = lignecommande;
    }
    public BigDecimal getQuantitelivree() {
        return this.quantitelivree;
    }
    
    public void setQuantitelivree(BigDecimal quantitelivree) {
        this.quantitelivree = quantitelivree;
    }




}


