package entity;
// Generated May 21, 2018 1:50:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Lignecommande generated by hbm2java
 */
public class Lignecommande  implements java.io.Serializable {


     private LignecommandeId id;
     private Commande commande;
     private Article article;
     private BigDecimal quantite;
     private Set detaillivraisons = new HashSet(0);

    public Lignecommande() {
    }

	
    public Lignecommande(LignecommandeId id, Commande commande, Article article, BigDecimal quantite) {
        this.id = id;
        this.commande = commande;
        this.article = article;
        this.quantite = quantite;
    }
    public Lignecommande(LignecommandeId id, Commande commande, Article article, BigDecimal quantite, Set detaillivraisons) {
       this.id = id;
       this.commande = commande;
       this.article = article;
       this.quantite = quantite;
       this.detaillivraisons = detaillivraisons;
    }
   
    public LignecommandeId getId() {
        return this.id;
    }
    
    public void setId(LignecommandeId id) {
        this.id = id;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public BigDecimal getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(BigDecimal quantite) {
        this.quantite = quantite;
    }
    public Set getDetaillivraisons() {
        return this.detaillivraisons;
    }
    
    public void setDetaillivraisons(Set detaillivraisons) {
        this.detaillivraisons = detaillivraisons;
    }




}


