package entity;
// Generated May 21, 2018 1:50:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Livraison generated by hbm2java
 */
public class Livraison  implements java.io.Serializable {


     private BigDecimal nolivraison;
     private Date datelivraison;
     private Set detaillivraisons = new HashSet(0);

    public Livraison() {
    }

	
    public Livraison(BigDecimal nolivraison, Date datelivraison) {
        this.nolivraison = nolivraison;
        this.datelivraison = datelivraison;
    }
    public Livraison(BigDecimal nolivraison, Date datelivraison, Set detaillivraisons) {
       this.nolivraison = nolivraison;
       this.datelivraison = datelivraison;
       this.detaillivraisons = detaillivraisons;
    }
   
    public BigDecimal getNolivraison() {
        return this.nolivraison;
    }
    
    public void setNolivraison(BigDecimal nolivraison) {
        this.nolivraison = nolivraison;
    }
    public Date getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(Date datelivraison) {
        this.datelivraison = datelivraison;
    }
    public Set getDetaillivraisons() {
        return this.detaillivraisons;
    }
    
    public void setDetaillivraisons(Set detaillivraisons) {
        this.detaillivraisons = detaillivraisons;
    }




}


